<h1 align='center'>Netflix Dataset Cleaning & Preparation </h1>

### Import dataset

In [11]:
import pandas as pd

In [16]:
df = pd.read_csv(r'E:\internship\Auspify\netflix_dataset.csv')

In [17]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 1.6 MB

#### Above Result shows that there is no null or missing value.

### Correct Data Type

In [5]:
df["date_added"] = pd.to_datetime(df["date_added"].str.strip()) ## Chnaged dtype str to datetime

In [6]:
# Extract the numbers and convert into integers
df["duration"] = df["duration"].str.extract(r'(\d+)').astype('int64')

In [7]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125,"Dramas, Independent Movies, International Movies"

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   datetime64[us]
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   int64
 9   listed_in     8790 non-null   str
dtypes: datetime64[us](1), int64(2), str(7)
memory usage: 1.4 MB

In [9]:
df.describe(include = 'all')

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
count,8790,8790,8790,8790,8790,8790,8790.000000,8790,8790.000000,8790
unique,8790,2,8787,4528,86,NaN,NaN,14,NaN,513
top,s1,Movie,9-Feb,Not Given,United States,NaN,NaN,TV-MA,NaN,"Dramas, International Movies"
freq,1,6126,2,2588,3240,NaN,NaN,3205,NaN,362
mean,NaN,NaN,NaN,NaN,NaN,2019-05-17 21:44:01.638225,2014.183163,NaN,69.934471,NaN
min,NaN,NaN,NaN,NaN,NaN,2008-01-01 00:00:00,1925.000000,NaN,1.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,2018-04-06 00:00:00,2013.000000,NaN,2.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,2019-07-03 00:00:00,2017.000000,NaN,88.500000,NaN
75%,NaN,NaN,NaN,NaN,NaN,2020-08-19 18:00:00,2019.000000,NaN,106.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,2021-09-25 00:00:00,2021.000000,NaN,312.000000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,8.825466,NaN,50.794433,NaN

### Check duplicates

In [10]:
df.duplicated().sum()

np.int64(0)

##### No duplicates found

### Check Formating Inconsistencies

In [11]:
print(df["type"].value_counts())
print()  
print(df["rating"].value_counts())

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [12]:
print(df["country"].nunique())

86

In [13]:
# Check country formatting
country_clean = df["country"].str.strip()

print("Extra spaces:", (df["country"] != country_clean).sum())

# Check case differences
print("Original unique:", df["country"].nunique())
print("Lowercase unique:", df["country"].str.lower().nunique())

Extra spaces: 0
Original unique: 86
Lowercase unique: 86

##### There is no formatting inconsistenc.

### Standardize Columns

In [14]:
# Standardize Rating
df["rating"] = df["rating"].str.strip().str.upper()

# Standardize Type
df["type"] = df["type"].str.strip().str.title()

In [15]:
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90,Documentaries
1,s3,Tv Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,Tv Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125,"Dramas, Independent Movies, International Movies"

### Save dataset as a CSV file

In [76]:
df.to_csv("cleaned_netflix_dataset.csv", index=False)

print(f"Export complete! Successfully saved {len(df)} rows to 'cleaned_netflix_dataset.csv'.")

Export complete! Successfully saved 8790 rows to 'cleaned_netflix_dataset.csv'.

### THE END